version: '3.8'

services:
  web:
    build:
      context: .
      args:
        # Build-time variables (for client-side)
        NEXT_PUBLIC_SECRET: ${NEXT_PUBLIC_SECRET}
    ports:
      - "3000:3000"
    environment:
      # Runtime variables (for server-side)
      - NODE_ENV=production
      - SECRET_KEY=${SECRET_KEY}
    # Enable for development hot reloading
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public
    restart: unless-stopped 